export const categories = [
    { name: 'New', icon: <i className="fa-solid fa-newspaper mx-2" style={{color: "red"}}></i> },
    { name: 'Coding', icon: <i className="fa-sharp fa-solid fa-code mx-2" style={{color: "red"}}></i> },
    { name: 'ReactJS', icon: <i className="fa-sharp fa-solid fa-code mx-2" style={{color: "red"}}></i> },
    { name: 'Music', icon: <i className="fa-solid fa-music mx-2" style={{color: "red"}}></i> },
    { name: 'Education', icon: <i className="fa-solid fa-school mx-2" style={{color: "red"}}></i> },
    { name: 'Podcast', icon: <i className="fa-solid fa-podcast mx-2" style={{color: "red"}}></i> },
    { name: 'Movie', icon: <i className="fa-solid fa-video mx-2" style={{color: "red"}}></i> },
    { name: 'Gaming', icon: <i className="fa-solid fa-headset mx-2" style={{color: "red"}}></i> },
    { name: 'Live', icon: <i className="fa-solid fa-tower-broadcast mx-2" style={{color: "red"}}></i> },
    { name: 'Sport', icon: <i className="fa-solid fa-volleyball mx-2" style={{color: "red"}}></i> },
    { name: 'Fashion', icon: <i className="fa-sharp fa-solid fa-person-dress mx-2" style={{color: "red"}}></i>},
    { name: 'Beauty', icon: <i className="fa-solid fa-heart mx-2" style={{color: "red"}}></i> },
    { name: 'Comedy', icon: <i className="fa-solid fa-masks-theater mx-2" style={{color: "red"}}></i> },
    { name: 'Gym', icon: <i className="fa-solid fa-dumbbell mx-2" style={{color: "red"}}></i>},
    { name: 'Crypto', icon: <i className="fa-solid fa-coins mx-2" style={{color: "red"}}></i> },
  ];